version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: net.serenity-bdd:serenity-single-page-report
    versions:
    - 2.3.13
    - 2.3.30
    - 2.3.31
    - 2.4.1
    - 2.4.2
    - 2.4.20
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: net.serenity-bdd:serenity-gradle-plugin
    versions:
    - 2.3.13
    - 2.3.31
    - 2.4.2
  - dependency-name: com.gorylenko.gradle-git-properties
    versions:
    - 2.2.4
    - 2.3.0
  - dependency-name: uk.gov.hmcts.java
    versions:
    - 0.12.6
    - 0.12.7
  - dependency-name: au.com.dius.pact
    versions:
    - 4.2.0
    - 4.2.2
    - 4.2.3
  - dependency-name: org.springframework.security:spring-security-web
    versions:
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-crypto
    versions:
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-core
    versions:
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-config
    versions:
    - 5.4.5
  - dependency-name: info.solidsoft.pitest
    versions:
    - 1.5.2
    - 1.6.0
  - dependency-name: org.pitest:pitest
    versions:
    - 1.6.2
    - 1.6.3
    - 1.6.4
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.36.0
    - 0.38.0
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
    - 3.12.0
  - dependency-name: com.sun.xml.bind:jaxb-core
    versions:
    - 3.0.0
  - dependency-name: javax.ws.rs:javax.ws.rs-api
    versions:
    - 2.1.1
  - dependency-name: org.springframework.security:spring-security-test
    versions:
    - 5.4.5
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.1
  - dependency-name: com.sun.xml.bind:jaxb-impl
    versions:
    - 3.0.0
  - dependency-name: info.solidsoft.gradle.pitest:gradle-pitest-plugin
    versions:
    - 1.5.2
  - dependency-name: io.rest-assured:rest-assured
    versions:
    - 4.3.3
  - dependency-name: uk.gov.hmcts.reform:properties-volume-spring-boot-starter
    versions:
    - 0.1.0
  - dependency-name: org.sonarsource.scanner.gradle:sonarqube-gradle-plugin
    versions:
    - 3.1.1
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.0
    - 6.1.1
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
    - 5.7.1
  - dependency-name: org.springframework.retry:spring-retry
    versions:
    - 1.3.1
  - dependency-name: io.jsonwebtoken:jjwt
    versions:
    - 0.9.1
  - dependency-name: io.spring.dependency-management
    versions:
    - 1.0.11.RELEASE
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1-jre
