version: '2.1'

services:
  submit-service:
    build:
      context: .
    image: probate/submit-service
    # image: docker.artifactory.reform.hmcts.net/probate/submit-service
    container_name: submit-service
    environment:
      - SERVER_PORT=8181
      - PROBATE_PERSISTENCE_HOSTNAME=localhost:8282
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 8181:8181

