---
  security:
    basic:
      enabled: false

  management:
    security:
      enabled: false
  
  mail:
    username: localhost
    password: dummyKey

    host: localhost
    port: 2525

    javaMailProperties.subject: Online Probate Application
    javaMailProperties.sender: dummySender@email.hmcts
    javaMailProperties.recipient: dummyTest@gmail.com

    javaMailProperties.mail.smtp.auth: false
    javaMailProperties.mail.smtp.ssl.enable: false

# THYMELEAF (ThymeleafAutoConfiguration)
  spring:
    application:
      name: probate-submit-service
    thymeleaf.check-template-location: true
    thymeleaf.prefix=classpath: /templates/
    thymeleaf.excluded-view-names: # comma-separated list of view names   that should be excluded from resolution
    thymeleaf.view-names: # comma-separated list of view names that can be resolved
    thymeleaf.suffix: .html
    thymeleaf.mode: HTML5
    thymeleaf.encoding: UTF-8
    thymeleaf.content-type: text/html # ;charset=<encoding> is added
    thymeleaf.cache: false # set to false for hot refresh

    messages:
      basename: messages
      cache-seconds: -1
      encoding: UTF-8

  server:
    port: 8181

  services:
    persistence:
      baseUrl: http://localhost:8282
      formdata.url:  ${services.persistence.baseUrl}/formdata
      submissions.url:  ${services.persistence.baseUrl}/submissions
      sequenceNumber.url:  ${services.persistence.baseUrl}/sequence-number

    coreCaseData:
      baseUrl: https://case-data-app.dev.ccd.reform.hmcts.net:4451
      url: ${services.coreCaseData.baseUrl}/citizens/%s/jurisdictions/PROBATE/case-types/GrantOfRepresentation
      enabled: ${USE_CCD:false}

  auth.provider.service.client:
    baseUrl: http://localhost:4502
    microservice: 'probate_backend'
    key: dummyKey
    tokenTimeToLiveInSeconds: '900'

  idam.s2s-auth.url: ${auth.provider.service.client.baseUrl}
  
  ccd:
    probate:
      fullName: fullName
      notApplyingKey: notApplyingKey
      isApplying: isApplying
      address: address
      email: email
      mobile: mobile
      hasOtherName: hasOtherName
      currentName: currentName
    ccd:  
      notApplyingExecutorName: notApplyingExecutorName    
      notApplyingExecutorReason: notApplyingExecutorReason
      value: value
      applyingExecutorName: applyingExecutorName
      applyingExecutorEmail: applyingExecutorEmail
      applyingExecutorPhoneNumber: applyingExecutorPhoneNumber
      applyingExecutorAddress: applyingExecutorAddress
      applyingExecutorOtherNames: applyingExecutorOtherNames
    reasonMap:
      optionDiedBefore: DiedBefore
      optionDiedAfter: DiedAfter
      optionPowerReserved: PowerReserved
      optionRenunciated: Renunciation
    dateMap:
      deceasedDob: deceasedDateOfBirth
      deceasedDod: deceasedDateOfDeath
      willDate: willDate
      willCodicilsDate: willLatestCodicilDate
    fieldMap:
      applicantIsExecutor: primaryApplicantIsApplying
      applicantFirstName: primaryApplicantForenames
      applicantLastName: primaryApplicantSurname
      applicantPhone: primaryApplicantPhoneNumber
      applicantEmail: primaryApplicantEmailAddress
      deceasedFirstname: deceasedForenames
      deceasedSurname: deceasedSurname
      willLeft: willExists
      willOriginal: willAccessOriginal
      willWithCodicils: willHasCodicils
      deceasedMarriedAfterDateOnWill: deceasedMarriedAfterWillOrCodicilDate
      noOfApplicants: numberOfApplicants
      noOfExecutors: numberOfExecutors
      ihtIdentifier: ihtReferenceNumber
      copiesUK: extraCopiesOfGrant
      copiesOverseas: outsideUKGrantCopies
      paymentReference: paymentReferenceNumber
      willCodicilsNumber: willNumberOfCodicils
      willCodicilsWithDate: willLatestCodicilHasDate
      deceasedAliasAssets: deceasedAnyOtherNames
    monetaryValueMap:
      ihtGrossValue: ihtGrossValue
      ihtNetValue: ihtNetValue
      totalFee: totalFee
    declarationMap:
      declaration: declaration
    legalStatementMap:
      legalStatement: legalStatement
    executorMap:
      executorsNotApplying: executorsNotApplying
      executorsApplying: executorsApplying
    aliasMap:  
      deceasedOtherNames: deceasedAliasNameList
    addressMap:
      applicantAddress: primaryApplicantAddress
      deceasedAddress: deceasedAddress

  logging:
    level:
      org.springframework.web: ERROR
      uk.gov.hmcts.probate: DEBUG
    pattern:
      console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

  azure:
    app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}

  registries:
    - name: oxford
      id: 0
      email: oxford@email.com
      address: |
        Line 1 Ox
        Line 2 Ox
        Line 3 Ox
        PostCode Ox
    - name: birmingham
      id: 1
      email: birmingham@email.com
      address: |
        Line 1 Bham
        Line 2 Bham
        Line 3 Bham
        PostCode Bham