apiVersion: v2
description: A Helm chart for the HMCTS probate-submit product
name: probate-submit-service
home: https://github.com/hmcts/probate-submit-service
version: 0.2.18
maintainers:
  - name: HMCTS Probate Team
    email: probate-action-group@HMCTS.NET
dependencies:
  - name: java
    version: 3.7.4
    repository: '@hmctspublic'
