description: A Helm chart for the HMCTS probate-submit product
name: probate-submit-service
home: https://github.com/hmcts/probate-submit-service
version: 0.1.3
maintainers:
  - name: HMCTS Probate Team
    email: probate-action-group@HMCTS.NET
