description: A Helm chart for the HMCTS probate product
name: probate-submit-service
home: https://github.com/hmcts/probate-submit-service
version: 0.1.1
maintainers:
  - name: HMCTS Probate Team
    email: Probate@hmcts.net