java:
  applicationPort: 8181
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: submit-service
    MAIL_JAVAMAILPROPERTIES_MAIL_SMTP_SSL_ENABLE: false
    MAIL_JAVAMAILPROPERTIES_MAIL_SMTP_AUTH: false
    SERVICES_CORECASEDATA_ENABLED: true
    MAIL_JAVAMAILPROPERTIES_SUBJECT: "Probate Application"
    PACT_BROKER_URL: pact-broker.platform.hmcts.net
    PACT_BROKER_PORT: 80
  image: 'https://hmcts.azurecr.io/hmcts/probate-submit-service:latest'

ccd-elasticsearch:
  ccd:
    ingressHost: default
    ingressIP: loopback
    consulIP: loopback

    definitionStoreApi:
      s2sKey: DUMMY

    apiGateway:
      s2sKey: DUMMY
      idamClientSecret: DUMMY

    dataStoreApi:
      s2sKey: DUMMY
      image: "hmcts.azurecr.io/hmcts/ccd-data-store-api:tim-debug"

    caseManagementWeb:
      enabled: true

    printApi:
      enabled: true # if you need access to the case print service then enable this
      s2sKey: DUMMY
      probateTemplateUrl: http://print-api-DUMMY