java:
  applicationPort: 8181
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: submit-service
    MAIL_JAVAMAILPROPERTIES_MAIL_SMTP_SSL_ENABLE: false
    MAIL_JAVAMAILPROPERTIES_MAIL_SMTP_AUTH: false
    SERVICES_CORECASEDATA_ENABLED: true
    MAIL_JAVAMAILPROPERTIES_SUBJECT: "Probate Application"
    PACT_BROKER_URL: pact-broker.platform.hmcts.net
    PACT_BROKER_PORT: 80
  image: hmctspublic.azurecr.io/probate/probate-submit-service:latest
    ingressHost: localhost