java:
  environment:
    SERVICES_PERSISTENCE_BASEURL: http://probate-persistence-service-aat.service.core-compute-aat.internal
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL : http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    SERVICES_CORECASEDATA_BASEURL : http://ccd-data-store-api-aat.service.core-compute-aat.internal
    AUTH_PROVIDER_SERVICE_CLIENT_KEY: ${S2S_AUTH_TOTP_SECRET}
    MAIL_USERNAME: ${PROBATE_SUB_MAIL_USERNAME}
    MAIL_PASSWORD: ${PROBATE_SUB_MAIL_PASSWORD}
    MAIL_HOST: ${PROBATE_SUB_MAIL_HOST}
    MAIL_PORT: ${PROBATE_SUB_MAIL_PORT}
    MAIL_JAVAMAILPROPERTIES_SENDER: ${PROBATE_SUB_MAIL_SENDER}
    MAIL_JAVAMAILPROPERTIES_RECIPIENT: ${PROBATE_SUB_MAIL_REC}
    AUTH_IDAM_CLIENT_BASEURL: https://idam-api.aat.platform.hmcts.net
  configmap:
    SPRING_APPLICATION_JSON : '{"registries":[{"address":"Principal Registry of the Family Division (PRFD)\nHMCTS Probate\nPO Box 12625\nHarlow\nCM20 9QE","name":"ctsc"}]}'

  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

ccd-elasticsearch:
  ccd:
    ingressHost: ${SERVICE_FQDN}
    ingressIP: ${INGRESS_IP}
    consulIP: ${CONSUL_LB_IP}

    definitionStoreApi:
      s2sKey: ${DEFINITION_STORE_S2S_KEY}

    apiGateway:
      s2sKey: ${API_GATEWAY_S2S_KEY}
      idamClientSecret: ${API_GATEWAY_IDAM_SECRET}

    dataStoreApi:
      s2sKey: ${DATA_STORE_S2S_KEY}
      image: "hmcts.azurecr.io/hmcts/ccd-data-store-api:tim-debug"

    caseManagementWeb:
      enabled: true

    printApi:
      enabled: true # if you need access to the case print service then enable this
      s2sKey: ${PRINT_S2S_KEY}
      probateTemplateUrl: http://print-api-${SERVICE_FQDN}

    importer:
      definitions:
        - https://raw.githubusercontent.com/hmcts/Probate-CCD-Import-Spreadsheets/master/spreadsheet/back-office/CCD_Probate_V04.32.01-Hlm.xlsx
      # location incorrect.. its not in b-o, do we need this sheet?   - https://raw.githubusercontent.com/hmcts/Probate-CCD-Import-Spreadsheets/master/spreadsheet/back-office/CCD_Probate_Legacy_V00.01-Dev.xlsx
      #      - https://github.com/hmcts/Probate-CCD-Import-Spreadsheets/raw/master/spreadsheet/CCD_Probate_V21.02-Dev.xlsx
      userRoles:
        - caseworker-probate
        - caseworker-probate-issuer
        - caseworker-probate-solicitor
        - citizen
        - caseworker-probate-examiner
